Import('env')
rpc_src = ['rpc.cpp']
rpc_sharedlib = env.SharedLibrary('simpleprotorpc', rpc_src)
rpc_staticlib = env.StaticLibrary('simpleprotorpc', rpc_src)
env.Install(env['LIBDIR'], rpc_sharedlib)
env.Install(env['LIBDIR'], rpc_staticlib)
env.Install(env['INCDIR'], 'rpc.h')
