// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "graphics.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* GraphicsTransaction_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GraphicsTransaction_reflection_ = NULL;
const ::google::protobuf::Descriptor* GraphicsMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GraphicsMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* ColorMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ColorMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* PointSizeMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PointSizeMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* CircleMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CircleMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* PointMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PointMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* LineMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LineMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* MapMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MapMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* ScaleMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ScaleMessage_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_graphics_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  GraphicsTransaction_descriptor_ = file->message_type(0);
  GraphicsTransaction::default_instance_ = new GraphicsTransaction();
  GraphicsTransaction_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GraphicsTransaction_descriptor_,
      GraphicsTransaction::default_instance_,
      GraphicsTransaction::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsTransaction, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsTransaction, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GraphicsTransaction_descriptor_, GraphicsTransaction::default_instance_);
  GraphicsMessage_descriptor_ = file->message_type(1);
  GraphicsMessage::default_instance_ = new GraphicsMessage();
  GraphicsMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GraphicsMessage_descriptor_,
      GraphicsMessage::default_instance_,
      GraphicsMessage::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GraphicsMessage_descriptor_, GraphicsMessage::default_instance_);
  ColorMessage_descriptor_ = file->message_type(2);
  ColorMessage::default_instance_ = new ColorMessage();
  ColorMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ColorMessage_descriptor_,
      ColorMessage::default_instance_,
      ColorMessage::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ColorMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ColorMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ColorMessage_descriptor_, ColorMessage::default_instance_);
  PointSizeMessage_descriptor_ = file->message_type(3);
  PointSizeMessage::default_instance_ = new PointSizeMessage();
  PointSizeMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PointSizeMessage_descriptor_,
      PointSizeMessage::default_instance_,
      PointSizeMessage::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointSizeMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointSizeMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PointSizeMessage_descriptor_, PointSizeMessage::default_instance_);
  CircleMessage_descriptor_ = file->message_type(4);
  CircleMessage::default_instance_ = new CircleMessage();
  CircleMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CircleMessage_descriptor_,
      CircleMessage::default_instance_,
      CircleMessage::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CircleMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CircleMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CircleMessage_descriptor_, CircleMessage::default_instance_);
  PointMessage_descriptor_ = file->message_type(5);
  PointMessage::default_instance_ = new PointMessage();
  PointMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PointMessage_descriptor_,
      PointMessage::default_instance_,
      PointMessage::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PointMessage_descriptor_, PointMessage::default_instance_);
  LineMessage_descriptor_ = file->message_type(6);
  LineMessage::default_instance_ = new LineMessage();
  LineMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LineMessage_descriptor_,
      LineMessage::default_instance_,
      LineMessage::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LineMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LineMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LineMessage_descriptor_, LineMessage::default_instance_);
  MapMessage_descriptor_ = file->message_type(7);
  MapMessage::default_instance_ = new MapMessage();
  MapMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MapMessage_descriptor_,
      MapMessage::default_instance_,
      MapMessage::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MapMessage_descriptor_, MapMessage::default_instance_);
  ScaleMessage_descriptor_ = file->message_type(8);
  ScaleMessage::default_instance_ = new ScaleMessage();
  ScaleMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ScaleMessage_descriptor_,
      ScaleMessage::default_instance_,
      ScaleMessage::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScaleMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScaleMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ScaleMessage_descriptor_, ScaleMessage::default_instance_);
  GraphicsTransaction::default_instance_->InitAsDefaultInstance();
  GraphicsMessage::default_instance_->InitAsDefaultInstance();
  ColorMessage::default_instance_->InitAsDefaultInstance();
  PointSizeMessage::default_instance_->InitAsDefaultInstance();
  CircleMessage::default_instance_->InitAsDefaultInstance();
  PointMessage::default_instance_->InitAsDefaultInstance();
  LineMessage::default_instance_->InitAsDefaultInstance();
  MapMessage::default_instance_->InitAsDefaultInstance();
  ScaleMessage::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_graphics_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\016graphics.proto\"S\n\023GraphicsTransaction\022"
    "!\n\007message\030\001 \003(\0132\020.GraphicsMessage\022\031\n\npe"
    "rsistent\030\002 \001(\010:\005false\"\350\001\n\017GraphicsMessag"
    "e\022\034\n\005color\030\001 \001(\0132\r.ColorMessage\022%\n\npoint"
    "_size\030\002 \001(\0132\021.PointSizeMessage\022\036\n\006circle"
    "\030\003 \001(\0132\016.CircleMessage\022\034\n\005point\030\004 \001(\0132\r."
    "PointMessage\022\032\n\004line\030\005 \001(\0132\014.LineMessage"
    "\022\030\n\003map\030\006 \001(\0132\013.MapMessage\022\034\n\005scale\030\007 \001("
    "\0132\r.ScaleMessage\"/\n\014ColorMessage\022\t\n\001r\030\001 "
    "\002(\005\022\t\n\001g\030\002 \002(\005\022\t\n\001b\030\003 \002(\005\"\036\n\020PointSizeMe"
    "ssage\022\n\n\002sz\030\001 \002(\001\"7\n\rCircleMessage\022\n\n\002cx"
    "\030\001 \002(\001\022\n\n\002cy\030\002 \002(\001\022\016\n\006radius\030\003 \002(\001\"$\n\014Po"
    "intMessage\022\t\n\001x\030\001 \002(\001\022\t\n\001y\030\002 \002(\001\"=\n\013Line"
    "Message\022\n\n\002x0\030\001 \002(\001\022\n\n\002y0\030\002 \002(\001\022\n\n\002x1\030\003 "
    "\002(\001\022\n\n\002y1\030\004 \002(\001\"g\n\nMapMessage\022\017\n\007xcenter"
    "\030\001 \002(\001\022\017\n\007ycenter\030\002 \002(\001\022\r\n\005scale\030\003 \002(\001\022\014"
    "\n\004xres\030\004 \002(\005\022\014\n\004yres\030\005 \002(\005\022\014\n\004data\030\006 \001(\014"
    "\"\035\n\014ScaleMessage\022\r\n\005scale\030\001 \002(\001", 711,
  &protobuf_BuildDesc_graphics_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_graphics_2eproto {
  StaticDescriptorInitializer_graphics_2eproto() {
    protobuf_BuildDesc_graphics_2eproto();
  }
} static_descriptor_initializer_graphics_2eproto_;


// ===================================================================



const int GraphicsTransaction::_offsets_[2] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsTransaction, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsTransaction, persistent_),
};

GraphicsTransaction::GraphicsTransaction()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    persistent_(false) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void GraphicsTransaction::InitAsDefaultInstance() {}

GraphicsTransaction::GraphicsTransaction(const GraphicsTransaction& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    persistent_(false) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

GraphicsTransaction::~GraphicsTransaction() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* GraphicsTransaction::descriptor() {
  if (GraphicsTransaction_descriptor_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return GraphicsTransaction_descriptor_;
}

const GraphicsTransaction& GraphicsTransaction::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return *default_instance_;
}

GraphicsTransaction* GraphicsTransaction::default_instance_ = NULL;

GraphicsTransaction* GraphicsTransaction::New() const {
  return new GraphicsTransaction;
}

const ::google::protobuf::Descriptor* GraphicsTransaction::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* GraphicsTransaction::GetReflection() const {
  if (GraphicsTransaction_reflection_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return GraphicsTransaction_reflection_;
}

// ===================================================================








const int GraphicsMessage::_offsets_[7] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsMessage, color_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsMessage, point_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsMessage, circle_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsMessage, point_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsMessage, line_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsMessage, map_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GraphicsMessage, scale_),
};

GraphicsMessage::GraphicsMessage()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    color_(NULL),
    point_size_(NULL),
    circle_(NULL),
    point_(NULL),
    line_(NULL),
    map_(NULL),
    scale_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void GraphicsMessage::InitAsDefaultInstance() {  color_ = const_cast< ::ColorMessage*>(&::ColorMessage::default_instance());
  point_size_ = const_cast< ::PointSizeMessage*>(&::PointSizeMessage::default_instance());
  circle_ = const_cast< ::CircleMessage*>(&::CircleMessage::default_instance());
  point_ = const_cast< ::PointMessage*>(&::PointMessage::default_instance());
  line_ = const_cast< ::LineMessage*>(&::LineMessage::default_instance());
  map_ = const_cast< ::MapMessage*>(&::MapMessage::default_instance());
  scale_ = const_cast< ::ScaleMessage*>(&::ScaleMessage::default_instance());
}

GraphicsMessage::GraphicsMessage(const GraphicsMessage& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    color_(NULL),
    point_size_(NULL),
    circle_(NULL),
    point_(NULL),
    line_(NULL),
    map_(NULL),
    scale_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

GraphicsMessage::~GraphicsMessage() {
  if (this != default_instance_) {
    delete color_;
    delete point_size_;
    delete circle_;
    delete point_;
    delete line_;
    delete map_;
    delete scale_;
  }
}

const ::google::protobuf::Descriptor* GraphicsMessage::descriptor() {
  if (GraphicsMessage_descriptor_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return GraphicsMessage_descriptor_;
}

const GraphicsMessage& GraphicsMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return *default_instance_;
}

GraphicsMessage* GraphicsMessage::default_instance_ = NULL;

GraphicsMessage* GraphicsMessage::New() const {
  return new GraphicsMessage;
}

const ::google::protobuf::Descriptor* GraphicsMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* GraphicsMessage::GetReflection() const {
  if (GraphicsMessage_reflection_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return GraphicsMessage_reflection_;
}

// ===================================================================




const int ColorMessage::_offsets_[3] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ColorMessage, r_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ColorMessage, g_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ColorMessage, b_),
};

ColorMessage::ColorMessage()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    r_(0),
    g_(0),
    b_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ColorMessage::InitAsDefaultInstance() {}

ColorMessage::ColorMessage(const ColorMessage& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    r_(0),
    g_(0),
    b_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ColorMessage::~ColorMessage() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* ColorMessage::descriptor() {
  if (ColorMessage_descriptor_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return ColorMessage_descriptor_;
}

const ColorMessage& ColorMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return *default_instance_;
}

ColorMessage* ColorMessage::default_instance_ = NULL;

ColorMessage* ColorMessage::New() const {
  return new ColorMessage;
}

const ::google::protobuf::Descriptor* ColorMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ColorMessage::GetReflection() const {
  if (ColorMessage_reflection_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return ColorMessage_reflection_;
}

// ===================================================================


const int PointSizeMessage::_offsets_[1] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointSizeMessage, sz_),
};

PointSizeMessage::PointSizeMessage()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    sz_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void PointSizeMessage::InitAsDefaultInstance() {}

PointSizeMessage::PointSizeMessage(const PointSizeMessage& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    sz_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

PointSizeMessage::~PointSizeMessage() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* PointSizeMessage::descriptor() {
  if (PointSizeMessage_descriptor_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return PointSizeMessage_descriptor_;
}

const PointSizeMessage& PointSizeMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return *default_instance_;
}

PointSizeMessage* PointSizeMessage::default_instance_ = NULL;

PointSizeMessage* PointSizeMessage::New() const {
  return new PointSizeMessage;
}

const ::google::protobuf::Descriptor* PointSizeMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* PointSizeMessage::GetReflection() const {
  if (PointSizeMessage_reflection_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return PointSizeMessage_reflection_;
}

// ===================================================================




const int CircleMessage::_offsets_[3] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CircleMessage, cx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CircleMessage, cy_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CircleMessage, radius_),
};

CircleMessage::CircleMessage()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    cx_(0),
    cy_(0),
    radius_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void CircleMessage::InitAsDefaultInstance() {}

CircleMessage::CircleMessage(const CircleMessage& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    cx_(0),
    cy_(0),
    radius_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

CircleMessage::~CircleMessage() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* CircleMessage::descriptor() {
  if (CircleMessage_descriptor_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return CircleMessage_descriptor_;
}

const CircleMessage& CircleMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return *default_instance_;
}

CircleMessage* CircleMessage::default_instance_ = NULL;

CircleMessage* CircleMessage::New() const {
  return new CircleMessage;
}

const ::google::protobuf::Descriptor* CircleMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* CircleMessage::GetReflection() const {
  if (CircleMessage_reflection_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return CircleMessage_reflection_;
}

// ===================================================================



const int PointMessage::_offsets_[2] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointMessage, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointMessage, y_),
};

PointMessage::PointMessage()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0),
    y_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void PointMessage::InitAsDefaultInstance() {}

PointMessage::PointMessage(const PointMessage& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0),
    y_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

PointMessage::~PointMessage() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* PointMessage::descriptor() {
  if (PointMessage_descriptor_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return PointMessage_descriptor_;
}

const PointMessage& PointMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return *default_instance_;
}

PointMessage* PointMessage::default_instance_ = NULL;

PointMessage* PointMessage::New() const {
  return new PointMessage;
}

const ::google::protobuf::Descriptor* PointMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* PointMessage::GetReflection() const {
  if (PointMessage_reflection_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return PointMessage_reflection_;
}

// ===================================================================





const int LineMessage::_offsets_[4] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LineMessage, x0_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LineMessage, y0_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LineMessage, x1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LineMessage, y1_),
};

LineMessage::LineMessage()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x0_(0),
    y0_(0),
    x1_(0),
    y1_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void LineMessage::InitAsDefaultInstance() {}

LineMessage::LineMessage(const LineMessage& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x0_(0),
    y0_(0),
    x1_(0),
    y1_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

LineMessage::~LineMessage() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* LineMessage::descriptor() {
  if (LineMessage_descriptor_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return LineMessage_descriptor_;
}

const LineMessage& LineMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return *default_instance_;
}

LineMessage* LineMessage::default_instance_ = NULL;

LineMessage* LineMessage::New() const {
  return new LineMessage;
}

const ::google::protobuf::Descriptor* LineMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* LineMessage::GetReflection() const {
  if (LineMessage_reflection_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return LineMessage_reflection_;
}

// ===================================================================






const ::std::string MapMessage::_default_data_;
const int MapMessage::_offsets_[6] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapMessage, xcenter_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapMessage, ycenter_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapMessage, scale_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapMessage, xres_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapMessage, yres_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapMessage, data_),
};

MapMessage::MapMessage()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    xcenter_(0),
    ycenter_(0),
    scale_(0),
    xres_(0),
    yres_(0),
    data_(const_cast< ::std::string*>(&_default_data_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void MapMessage::InitAsDefaultInstance() {}

MapMessage::MapMessage(const MapMessage& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    xcenter_(0),
    ycenter_(0),
    scale_(0),
    xres_(0),
    yres_(0),
    data_(const_cast< ::std::string*>(&_default_data_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

MapMessage::~MapMessage() {
  if (data_ != &_default_data_) {
    delete data_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* MapMessage::descriptor() {
  if (MapMessage_descriptor_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return MapMessage_descriptor_;
}

const MapMessage& MapMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return *default_instance_;
}

MapMessage* MapMessage::default_instance_ = NULL;

MapMessage* MapMessage::New() const {
  return new MapMessage;
}

const ::google::protobuf::Descriptor* MapMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* MapMessage::GetReflection() const {
  if (MapMessage_reflection_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return MapMessage_reflection_;
}

// ===================================================================


const int ScaleMessage::_offsets_[1] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ScaleMessage, scale_),
};

ScaleMessage::ScaleMessage()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    scale_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void ScaleMessage::InitAsDefaultInstance() {}

ScaleMessage::ScaleMessage(const ScaleMessage& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    scale_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

ScaleMessage::~ScaleMessage() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* ScaleMessage::descriptor() {
  if (ScaleMessage_descriptor_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return ScaleMessage_descriptor_;
}

const ScaleMessage& ScaleMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return *default_instance_;
}

ScaleMessage* ScaleMessage::default_instance_ = NULL;

ScaleMessage* ScaleMessage::New() const {
  return new ScaleMessage;
}

const ::google::protobuf::Descriptor* ScaleMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* ScaleMessage::GetReflection() const {
  if (ScaleMessage_reflection_ == NULL) protobuf_BuildDesc_graphics_2eproto();
  return ScaleMessage_reflection_;
}
